#!/usr/bin/env bash
#
# Bootstraps the Hono Guestbook example by:
#   1. Creating an Auth0 "Regular Web Application" in your active tenant.
#   2. Configuring its callback / logout URLs for local development.
#   3. Generating a session encryption key.
#   4. Writing a ready-to-use .dev.vars file.
#
# Requires: auth0 CLI (logged in), jq, openssl.
# Set AUTH0_TENANT to use a non-default tenant (e.g. AUTH0_TENANT=other.auth0.com npm run setup).

set -euo pipefail

APP_NAME="${APP_NAME:-Hono Guestbook}"
APP_DESCRIPTION="Hono + Cloudflare Workers guestbook example"
BASE_URL="http://localhost:8787"
DEV_VARS_FILE=".dev.vars"

# 1. Preflight ---------------------------------------------------------------
require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "✗ '$1' is required but was not found on PATH." >&2
    echo "  $2" >&2
    exit 1
  }
}

require auth0   "Install: https://auth0.github.io/auth0-cli/  (e.g. brew install auth0/auth0-cli/auth0)"
require jq      "Install: https://stedolan.github.io/jq/    (e.g. brew install jq)"
require openssl "Install: openssl is part of most base systems. On macOS, it ships with the OS."

# 2. Login check -------------------------------------------------------------
TENANTS_JSON="$(auth0 tenants list --json 2>/dev/null || true)"
if [[ -z "$TENANTS_JSON" || "$TENANTS_JSON" == "null" || "$TENANTS_JSON" == "[]" ]]; then
  echo "✗ No Auth0 tenants configured. Run 'auth0 login' first." >&2
  exit 1
fi

# 3. No-clobber --------------------------------------------------------------
if [[ -e "$DEV_VARS_FILE" ]]; then
  echo "✗ $DEV_VARS_FILE already exists — refusing to overwrite." >&2
  echo "  Remove it first:  rm $DEV_VARS_FILE" >&2
  exit 1
fi

# 4. Resolve tenant ----------------------------------------------------------
TENANT_FLAG=()
if [[ -n "${AUTH0_TENANT:-}" ]]; then
  AUTH0_DOMAIN="$AUTH0_TENANT"
  TENANT_FLAG=(--tenant "$AUTH0_TENANT")
else
  AUTH0_DOMAIN="$(echo "$TENANTS_JSON" | jq -r '.[] | select(.active==true) | .name')"
  if [[ -z "$AUTH0_DOMAIN" || "$AUTH0_DOMAIN" == "null" ]]; then
    echo "✗ Could not determine active tenant from 'auth0 tenants list'." >&2
    echo "  Set one with 'auth0 tenants use', or pass AUTH0_TENANT=..." >&2
    exit 1
  fi
fi

echo "→ Tenant: $AUTH0_DOMAIN"

# 5. Warm up the CLI's access token ------------------------------------------
# The Auth0 CLI silently mixes interactive re-auth prompts with the stdout of
# the command that triggered them, which corrupts --json output. Make a cheap
# Management API call first so any re-auth happens *before* the create call.
auth0 apps list ${TENANT_FLAG[@]+"${TENANT_FLAG[@]}"} --number 1 --json >/dev/null

# 6. Create the application --------------------------------------------------
echo "→ Creating Auth0 application \"$APP_NAME\"..."
APP_JSON="$(auth0 apps create \
  ${TENANT_FLAG[@]+"${TENANT_FLAG[@]}"} \
  --name "$APP_NAME" \
  --type regular \
  --description "$APP_DESCRIPTION" \
  --callbacks "$BASE_URL/auth/callback" \
  --logout-urls "$BASE_URL" \
  --reveal-secrets \
  --json)"

CLIENT_ID="$(echo "$APP_JSON" | jq -r '.client_id // empty')"
CLIENT_SECRET="$(echo "$APP_JSON" | jq -r '.client_secret // empty')"

if [[ -z "$CLIENT_ID" || -z "$CLIENT_SECRET" ]]; then
  echo "✗ Failed to read client_id / client_secret from auth0 apps create output." >&2
  echo "  Raw response:" >&2
  echo "$APP_JSON" | jq . >&2 || echo "$APP_JSON" >&2
  exit 1
fi

# 6. Generate session key ----------------------------------------------------
SESSION_KEY="$(openssl rand -hex 32)"

# 7. Write .dev.vars ---------------------------------------------------------
umask 077
cat > "$DEV_VARS_FILE" <<EOF
# Generated by scripts/setup-auth0.sh on $(date)
AUTH0_DOMAIN=$AUTH0_DOMAIN
AUTH0_CLIENT_ID=$CLIENT_ID
AUTH0_CLIENT_SECRET=$CLIENT_SECRET
BASE_URL=$BASE_URL
AUTH0_SESSION_ENCRYPTION_KEY=$SESSION_KEY
EOF

# 8. Done --------------------------------------------------------------------
MASKED_ID="${CLIENT_ID:0:6}…${CLIENT_ID: -4}"
echo "✓ Created application \"$APP_NAME\" (client_id $MASKED_ID)"
echo "✓ Wrote $DEV_VARS_FILE"
echo
echo "Next:"
echo "  npx wrangler kv namespace create GUESTBOOK   # one-time, paste id into wrangler.jsonc"
echo "  npm run cf-typegen"
echo "  npm run dev"
